workflows:
  build-xcframework:
    name: Build iOS XCFramework
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - name: Build XCFramework
        script: |
          ./gradlew :shared:assembleXCFramework
    artifacts:
      - shared/build/XCFrameworks/release/**/* 