name: Build iOS Framework

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Kotlin
        uses: fwilhe2/setup-kotlin@v1

      - name: Build iOS framework
        run: ./gradlew :shared:assembleXCFramework

      - name: Upload XCFramework
        uses: actions/upload-artifact@v4
        with:
          name: WakeOnLanShared.xcframework
          path: shared/build/XCFrameworks/release/ 